[theme]
base = "light"
primaryColor = "#527343"
backgroundColor = "#F6F7F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#192722"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
